web_env:
  database:
    host: 127.0.0.1
    port: 3306
    database: autotest1
    user: root
    password: qwert789456
    charset: utf-8

run_env:
  host:
    test: 192.168.7.241
    prep: 192.168.9.168
    prod: sdfjksdf


